In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import pdr

In [2]:
# df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header = None)
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wpbc.data ', header = None)

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,119513,N,31,18.02,27.60,117.50,1013.0,0.09489,0.1036,0.1086,...,139.70,1436.0,0.1195,0.1926,0.3140,0.1170,0.2677,0.08113,5.0,5
1,8423,N,61,17.99,10.38,122.80,1001.0,0.11840,0.2776,0.3001,...,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,3.0,2
2,842517,N,116,21.37,17.44,137.50,1373.0,0.08836,0.1189,0.1255,...,159.10,1949.0,0.1188,0.3449,0.3414,0.2032,0.4334,0.09067,2.5,0
3,843483,N,123,11.42,20.38,77.58,386.1,0.14250,0.2839,0.2414,...,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,2.0,0
4,843584,R,27,20.29,14.34,135.10,1297.0,0.10030,0.1328,0.1980,...,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,3.5,0

In [4]:
w = np.zeros(df.shape[0])
thresh = 0.5

In [5]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34],
           dtype='int64')

In [6]:
x = df.drop([1], axis=1)
y = df[1].map({'N': -1, 'R': 1})

In [7]:
x.head()

,0,2,3,4,5,6,7,8,9,10,...,25,26,27,28,29,30,31,32,33,34
0,119513,31,18.02,27.60,117.50,1013.0,0.09489,0.1036,0.1086,0.07055,...,139.70,1436.0,0.1195,0.1926,0.3140,0.1170,0.2677,0.08113,5.0,5
1,8423,61,17.99,10.38,122.80,1001.0,0.11840,0.2776,0.3001,0.14710,...,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,3.0,2
2,842517,116,21.37,17.44,137.50,1373.0,0.08836,0.1189,0.1255,0.08180,...,159.10,1949.0,0.1188,0.3449,0.3414,0.2032,0.4334,0.09067,2.5,0
3,843483,123,11.42,20.38,77.58,386.1,0.14250,0.2839,0.2414,0.10520,...,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,2.0,0
4,843584,27,20.29,14.34,135.10,1297.0,0.10030,0.1328,0.1980,0.10430,...,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,3.5,0

In [8]:
len(y[y == 1])

47

In [12]:
class Adaline(object):
    def __init__(self, learningRate = 0.01, itereation = 50):
        self.learningRate = learningRate
        self.itereation = itereation
    
    def fit(self, X, Y):
        self.weights = np.zeros(1 + X.shape[1])
        self.cost = []

        for i in range(self.itereation):
            output = self.activation(X) 
            errors = (Y - output)
            self.weights[1:] += self.learningRate * X.T.dot(errors)
            self.weights[0] += self.learningRate * errors.sum()
            cost = (errors ** 2).sum() / 2.0
            self.cost.append(cost)
            
    def predict(self, X) -> np.ndarray:
        return np.where(self.activation(X) >= 0.0, 1, -1)
    
    def activation(self, X) -> np.ndarray:
        return X.dot(self.weights[1:]) + self.weights[0]

In [13]:
model = Adaline(learningRate = 0.01, itereation = 50)

In [14]:
model.fit(x, y)

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
# Plot the training error
plt.plot(range(1, len(model.cost) + 1), model.cost, marker = 'o', color = 'red')
plt.xlabel('Epochs')
plt.ylabel('Sum-squared-error')
plt.show()

In [ ]:
# Plot the decision boundary
pdr.plot_decision_regions(X_std, y, classifier = model1)
plt.title('Adaline - Gradient Descent')
plt.xlabel('sepal length [standardized')
plt.ylabel('petal length [standardized]')
plt.legend(loc = 'upper left')
plt.show()